### ISSUE TITLE
[EPIC] Model support dashboard (v2)

### ISSUE THREAD

**Issue by mudler** [mudler/LocalAI#1126]
This epic is a major tracker for all the backends additions that should be part of LocalAI v2 and ongoing efforts.

The objective is to release a v2 which deprecates old models which are now superseded, plus adding a new set. In order to achieve this my idea is to clean up the current state and start pinning dependencies for all the backends which requires specific environment settings (python-based ones).

Some backends will be deprecated as superseded, as such some repositories will be archived (TBD yet). 

## Backends:

- [x] https://github.com/go-skynet/LocalAI/issues/1055
- [x] https://github.com/go-skynet/LocalAI/issues/1054
- [x] https://github.com/go-skynet/LocalAI/issues/1053
- [x] https://github.com/go-skynet/LocalAI/issues/1016
- [x] https://github.com/go-skynet/LocalAI/issues/1015
- [x] https://github.com/go-skynet/LocalAI/issues/1154
- [x] https://github.com/mudler/LocalAI/pull/1448 
- [x] #1348
- [x] #1262
- [x] https://github.com/mudler/LocalAI/issues/1162
- [x] https://github.com/mudler/LocalAI/pull/1026 
- [x] https://github.com/mudler/LocalAI/issues/1174
- [x] https://github.com/mudler/LocalAI/issues/1370
- [x] #1380
- [x] https://github.com/mudler/LocalAI/pull/1384
- [x]  https://github.com/mudler/LocalAI/pull/1442
- [x] #1464
- [x] https://github.com/mudler/LocalAI/pull/1387
- [x] #1588
- [x] https://github.com/mudler/LocalAI/issues/1392
- [x] https://github.com/mudler/LocalAI/issues/1438
- [ ] https://github.com/mudler/LocalAI/issues/1529
- [x] #1639
- [ ] https://github.com/mudler/LocalAI/issues/1538
- [ ] https://github.com/VikParuchuri/surya
- [x] #1638
- [x] #1636
- [ ] https://github.com/magic-research/magic-animate
- [x] #1637
- [ ] #1261
- [x] #1640
- [ ] #1263
- [ ] #915 
- [ ] #839 
- [ ] #1056 
- [x] #754 
- [ ] https://github.com/go-skynet/LocalAI/issues/939
- [x] https://github.com/go-skynet/LocalAI/issues/1110
- [x] https://github.com/mudler/LocalAI/issues/1028
- [ ] https://github.com/chenxwh/insanely-fast-whisper
- [ ] https://twitter.com/ggerganov/status/1724898446770069983
- [ ] https://llm.mlc.ai/docs/deploy/python.html
- [ ] vit.cpp
- [ ] https://github.com/penghao-wu/vstar
- [x] #1497
- [ ] #1539
- [ ] Tinygrad ( https://github.com/tinygrad/tinygrad/blob/master/examples/llama3.py )
- [ ] https://github.com/mudler/LocalAI/issues/917
- [ ] https://github.com/mudler/LocalAI/issues/1648
- [ ] #1649
- [ ] https://github.com/mudler/LocalAI/issues/1658
- [x] https://github.com/mudler/LocalAI/issues/1653
- [ ] https://github.com/mudler/LocalAI/issues/1647
- [x] #1592 
- [ ] https://github.com/apple/ml-mgie
- [ ] https://github.com/Zyphra/BlackMamba
- [ ] https://github.com/PKU-YuanGroup/MoE-LLaVA
- [ ] https://github.com/PKU-YuanGroup/Video-LLaVA
- [ ] https://github.com/LargeWorldModel/LWM
- [ ] https://github.com/Stability-AI/StableCascade/blob/master/inference%2Ftext_to_image.ipynb
- [x] https://github.com/mudler/LocalAI/issues/1722
- [x] https://github.com/myshell-ai/MeloTTS
- [ ] https://github.com/mudler/LocalAI/issues/1819
- [ ] https://github.com/roboflow/supervision
- [ ] https://github.com/Rudrabha/Wav2Lip
- [ ] https://github.com/jasonppy/VoiceCraft
- [ ] https://github.com/PKU-YuanGroup/Open-Sora-Plan
- [ ] https://github.com/mudler/LocalAI/issues/2010
- [x] https://github.com/mudler/LocalAI/issues/2018
- [x] https://github.com/mudler/LocalAI/pull/2027
- [ ] https://huggingface.co/nateraw/musicgen-songstarter-v0.2?s=09
- [x] https://github.com/PABannier/bark.cpp
- [x] https://github.com/mudler/LocalAI/issues/2318
- [ ] https://github.com/systran/faster-whisper
- [ ] https://github.com/mudler/LocalAI/issues/3375
- [ ] https://github.com/mudler/LocalAI/issues/2441
- [ ] https://github.com/fishaudio/fish-speech
- [ ] https://github.com/ictnlp/LLaMA-Omni
- [ ] https://github.com/mudler/LocalAI/issues/3628
- [ ] Moshi https://github.com/kyutai-labs/moshi/blob/main/moshi%2FREADME.md
- [ ] https://github.com/mudler/LocalAI/issues/3602
- [ ] https://github.com/baaivision/Emu3
- [ ] https://github.com/lucidrains/e2-tts-pytorch
- [ ] https://github.com/SWivid/F5-TTS
- [ ] https://github.com/homebrewltd/ichigo
- [ ] https://github.com/jy0205/Pyramid-Flow
- [ ] https://github.com/mudler/LocalAI/issues/3966
- [ ] https://github.com/Tencent/HunyuanVideo
- [x] https://github.com/ggerganov/llama.cpp/pull/10784
- [ ] https://github.com/SesameAILabs/csm
- [ ] https://docs.sglang.ai/start/install.html
- [ ] https://github.com/mudler/LocalAI/issues/5248
- [ ] https://github.com/mudler/LocalAI/issues/5447

**Comment by Aisuko** [comment]
I am thinking here, Should we need to have a outline likes below:

- [ ] C++
   - [ ] llama.cpp series LLM)
- [ ] Python
   - [ ]Huggingface
   - autoGPT
- [ ] Rust
   - rustformers
   - candle 

If we keep this in mind, we can split the model to the specific backend. For example, I saw the Qwen LLM mentioned their C++ implementation of it "working in the same way as llama.cpp". So, maybe it can be loaded by using llama.cpp. It should be compatible with C++ our backend.

**Comment by mudler** [comment]
conda branch was merged in https://github.com/mudler/LocalAI/pull/1144 . I'm looking now into make the llama.cpp backend on par with llama-go and also add llava support to it.

I'm going to refactor and re-layout things in the new `backend` directory too

**Comment by Aisuko** [comment]
@mudler thank you for mentioning. Here are some questions(second, and third one) may need you help https://github.com/mudler/LocalAI/pull/1180#discussion_r1382301643. Here what I am thinking is that we can use a tiny model to test the Rust backend features. And make sure everything ok. 

If everything ok. We can add other LLMs. I have plan to support Llama2(60% finished but it still has an issue), whisper, and  also support `onnex` format.

**Comment by mudler** [comment]
Breaking re-layout PR: https://github.com/mudler/LocalAI/pull/1279

**Comment by muka** [comment]
I may start looking into #1273 while this progresses. What do you think ?

**Comment by mudler** [comment]
> I may start looking into #1273 while this progresses. What do you think ?

please feel free to go ahead, there are many pieces involved in here, any help is more than appreciated :+1:

**Comment by mudler** [comment]
> caching/preloading of transformer and similar models, these are currently automatically loaded on startup into `/root/.cache/huggingface/`. It seems to be enough to set `TRANSFORMERS_CACHE` in the environment to the models folder, so maybe this only requires a documentation addition.

in https://github.com/mudler/LocalAI/pull/1746 I'm taking care of automatically binding the HF cache variables to the `models` directories if not set already

**Comment by mudler** [comment]
Closing.  Now we have an extensible backend system which allow to write and add backends as OCI images.

We are tracking all tickets and enhancements to the backends to add to LocalAI  separately with the "Roadmap" label: https://github.com/mudler/LocalAI/issues?q=is%3Aissue%20state%3Aopen%20label%3Aroadmap .
